@startuml
start
    partition #yellow "**Extração**" {
        repeat :Abrindo arquivo de fonte de dados;
            :Ler conteúdo do arquivo;
            :Identificar elemento de período/tempo;
            :Guardar em memória;
        backward:Identifica próximo a ser lido;
        repeat while (Tem mais arquivos a serem lidos?) is (Sim)
    }

    partition #PeachPuff "**Análise Inicial**" {
        :Identifica consumo por unidade federativa e separa por período;
        :Identifica consumo associado às regiões administrativas e separa por período;
        :Identifica geração por unidade federativa ou região e separa por período;
        :Grava no banco;
    }

    partition #lightGreen "**Análise Tarifária por Período e Fonte Geradora**" {
        :Varre base em busca de pontos de mudança de tarifa;
        repeat :Resgata dados de consumo para ponto de mudança de tarifa;
            :Busca mudanças de consumo imediatamente antes;
            :Identifica percentuais de produção por fonte imediatamente antes;
            :Busca mudanças de consumo imediatamente depois;
            :Identifica percentuais de produção por fonte imediatamente depois;
            :Grava o comparativo no banco;
        backward:Identifica próximo ponto de mudança de tarifa a ser analisado;
        repeat while (Tem mais pontos onde há mudança de tarifa?) is (Sim)
    }

    :Exibe análise feita em dashboard/painel/Tableau;
stop
@enduml